name: Publish to pkg.go.dev

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Create version script
      run: |
        echo '#!/bin/bash' > get_version.sh
        echo 'echo ${GITHUB_REF#refs/tags/}' >> get_version.sh
        chmod +x get_version.sh

    - name: Get the version
      id: get_version
      run: echo "VERSION=$(./get_version.sh)" >> $GITHUB_ENV

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build ./...

    - name: Publish
      run: |
        GOPROXY=proxy.golang.org go list -m github.com/janpreet/kado-ai@$VERSION
      env:
        GOPROXY: proxy.golang.org